services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8G
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=+S 4:4 +A 128
      - RABBITMQ_SERVER_ADDITIONAL_CONFIG=vm_memory_high_watermark.relative=0.6
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - coffee_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  connection-node:
    container_name: connection-node
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - SERVER_PORT=12345
    volumes:
      - ./config.ini:/config.ini   
    networks:
      - coffee_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "12345:12345"

volumes:
  rabbitmq_data:

networks:
  coffee_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
